name: "Docker-Pipeline"

on: [push]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Login to docker hub"
        if: success()
        uses: "actions-hub/docker/login@master"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build dev image"
        if: success()
        run: docker build -t ${GITHUB_REPOSITORY}:dev --file dev.Dockerfile .

      - name: "Build prod image"
        if: success()
        run: docker build -t ${GITHUB_REPOSITORY}:latest --file prod.Dockerfile .

      - name: "Push to docker registry"
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:latest
